name: noteflow_app
description: Convert music files to piano sheet music.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  dio: ^5.4.0
  firebase_core: ^2.25.0
  firebase_auth: ^4.17.0
  flutter_midi_pro: ^3.1.6
  file_picker: ^6.1.1
  # record: ^5.2.1  # TODO: re-enable when targeting mobile
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  web: ^0.5.1
  purchases_flutter: ^6.17.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/soundfonts/
